title: Devdalus Wiki
description: Tech Archive for project Devdalus
theme: just-the-docs
favicon_ico: "/assets/images/devdalus.ico"


url: https://DevdaIus.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
