title: Devdalus Tech Wiki
description: Tech Archive for project Devdalus
theme: just-the-docs

url: https://DevdaIus.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
